%YAML:1.0

imu: 0
num_of_cam: 2

imu_topic: ""
image0_topic: "/camera/image"
image1_topic: "/camera1/image"
output_path: "~/output/"

cam0_calib: "cam0_pinhole.yaml"
cam1_calib: "cam1_pinhole.yaml"
image_width: 640
image_height: 480

estimate_extrinsic: 0

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.0, 0.0, -1.0, 0.0,
          -1.0, 0.0, 0.0, 0.05,
          0.0, 1.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 1.0]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.0, 0.0, -1.0, 0.0,
          -1.0, 0.0, 0.0, -0.05,
          0.0, 1.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 1.0]

use_gpu: 0
use_gpu_acc_flow: 0
use_gpu_ceres: 0

multiple_thread: 1

max_cnt: 200
min_dist: 25
freq: 0
F_threshold: 1.0
show_track: 1
flow_back: 1

max_solver_time: 0.04
max_num_iterations: 8
keyframe_parallax: 5.0

acc_n: 0.2
gyr_n: 0.2
acc_w: 0.002
gyr_w: 0.0002
g_norm: 9.81007

estimate_td: 0
td: 0.0

load_previous_pose_graph: 0
pose_graph_save_path: "~/output/pose_graph/"
save_image: 0
